### ISSUE TITLE
参考说明文档创建Application实体时出现无效内存访问错误

### ISSUE THREAD

**Issue by mamimaka** [pnmocap/MocapApi#11]
我参照说明文档创建了Application实体，但在调试过程中报错，希望能够得到帮助，情况如下：
![938e7f5577778bf842355f0dbe29f91](https://user-images.githubusercontent.com/57143134/199276081-b06ea8eb-1247-49af-856a-04a1d1f44d29.jpg)

**Comment by mamimaka** [comment]
我使用的IDE是DEV-C++

**Comment by locobrain** [comment]
你的对话框挡住了关键代码，请问是在执行哪行代码 的时候 弹出了该 错误

**Comment by mamimaka** [comment]
![微信图片_20221102093509](https://user-images.githubusercontent.com/57143134/199374239-66b7f8d6-c121-45cc-8b9d-01d17786c545.jpg)
你好shi'z是在执行MCPGetGenericInterface()时出现了该错误

**Comment by locobrain** [comment]
第一个函数就挂了，请查链接函数入口 那儿怎么处理的？另外有没有把MocapApi.dll拷贝 到执行目录

**Comment by mamimaka** [comment]
链接函数入口的问题我等会检查一下，现在我发现我注释掉第一个函数之后，后面的函数调试时也还是会报相同的错误，或许是我dll没导入成功。我再检查一下dll导入的问题，我目前是把dll放在项目的文件夹里，并配置到了项目的链接和库目录里。

**Comment by mamimaka** [comment]
这个问题解决啦，就是dll没成功导入的问题。我在代码里添加LoadLibrary函数导入dll就行了。谢谢您的解答啦
