### ISSUE TITLE
Cannot connect Axis Studio via tcp on HoloLens

### ISSUE THREAD

**Issue by wy-luke** [pnmocap/MocapApi#9]
My app runs on HoloLens, which means another computer. 

It need to connect Axis Studio via Lan, but I've tried all my local IP, and none worked.

In Unity, which means same computer with Axis Studio, it runs well.

In your code, TCP was connected in the begining. So I make your connect function, `ToggleConnect()` in `NeuronSourceManager` public. So I can change IP address and connect again. 

After changing `GetComponent<NeuronSourceManager>().address`, I'll call `<NeuronSourceManager>().ToggleConnect();`

These code runs well in Unity. But it doesn't work in HoloLens. 

My computer that running Axis Studio connected same WIFI with HoloLens.

Thanks!

**Comment by locobrain** [comment]
We haven't tried it on HoloLens, in theory it should be like you mentioned earlier, you can try using UDP
